### ISSUE TITLE
Add Kafdrop to Kafka

### ISSUE THREAD

**Issue by marcalwestf** [erpya/adempiere-ui-gateway#74]
Kafdrop (https://github.com/obsidiandynamics/kafdrop) is a tool to administer topics, partitions, records, user groups, etc. in Kafka.

Though it is not recommended to use it in a production stack, it may be of great help when testing or debugging.

In our case, it would be added to the "develop" stack.

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  , @yamelsenih :   [Here](https://github.com/obsidiandynamics/kafdrop/blob/master/docker-compose/kafka-kafdrop/docker-compose.yaml) an example of integrating Kafdrop to Kafka with Docker Compose.

The yml file would look as follows:
```
version: "2"
services:
:
:
 # Here begins Kafdrop
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
 # Here ends Kafdrop     
:
:
```

We would only need to modify it adding the constants and using them in the yml file.

**Comment by EdwinBetanc0urt** [comment]
I think @marcalwestf is fine with the change I uploaded about `OpenSearch Dashboards` https://github.com/adempiere/adempiere-ui-gateway/pull/72, for development cases it improves a lot the data management, for a first delivery it is fine that it is only in the development stack.

Later it will be evaluated if it is added to the other stacks, since at least `OpenSearch Dashboards` allows basic authentication, `OpenID` and `SAML` https://opensearch.org/docs/latest/security/configuration/multi-auth/.

**Comment by marcalwestf** [comment]
Hi @EdwinBetanc0urt , @yamelsenih  ,
I tried to include a Kafdrop service into Kafka, but is doesn't work.

First: the default port of Kafdrop (9000) is already taken by **s3.storage**
After running` ./start-all.sh` I got the following error message:
`Error response from daemon: driver failed programming external connectivity on endpoint adempiere-ui-gateway.s3.storage (b3aa9334748ea2633ca27526812f453f452d651ded34f1e56c3d228262276cd4): Error starting userland proxy: listen tcp4 0.0.0.0:9000: bind: address already in use`
I solved it by changing the external port of Kafdrop to 19000.

Here we can later think of a solution about which is the default port of s3.storage.

Then I run again` ./start-all.sh`
Trying to open Kafdrop by running in the browser **localhost:19000** yields an error
```
Internal Server Error
A 500 error has occurred: Request processing failed:
 kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: 
org.apache.kafka.common.errors.TimeoutException: 
Timed out waiting for a node assignment. Call: listNodes 
```
After several unsuccessful tries, I decided to test Kafka as it is, without changes, before even trying to add Kafdrop.
It seems to me that Kafka is started, but it is not listening.

Thus I have two questions: 
- does Kafka runs correctly as of now (branch **main**)?
- how can I test if the _kafka_ service is running correctly?

The reason: I think that with the current version, Kafka has an error:

Here is what I have done so far:
1.- Start all services with `./start-all-sh`
      The Kafka container seems to be healthy:
![image](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/0df54d54-3238-4dcb-a577-89c3de492f33)

2.- Inspect kafka container and look at logs
`docker container inspect adempiere-ui-gateway.kafka`
![image](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/68c568f0-731b-4c8b-a4f8-1b033fe571fa)

3.- See log if everything is OK.
`sudo less /var/lib/docker/containers/../..-json.log`
      Here I find in the logs an error:
![image](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/3db0b655-08d5-4480-aba7-ef6cf28f5eff)
![image](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/9320e35d-fc55-45b4-8734-42571139ed9d)

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf to confirm that kafka is working correctly you raise the stack of cache or develop, in the default database that raises already has added the xml of this project https://github.com/adempiere/adempiere-kafka-connector. Before executing the steps indicated in that project to export the application dictionary I recommend you to delete the existing open search indexes.

Then following the steps of running the `Export Dictionary Definition` process in open search you should see the new indexes. Basically `OpenSearch Gateway RS` subscribes to the queue, that process sends to the kafka queue, then `OpenSearch Gateway RS` creates in `OpenSearch` the new indexes.

**Comment by marcalwestf** [comment]
additional information: the Kafdrop log reports that t cannot connect to Kafka:
![image](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/56777030-8ed4-4332-a0e5-bb8715c0ea48)

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf, the port where this service lifts can be configured with the variable `SERVER_PORT`.

![imagen](https://github.com/adempiere/adempiere-ui-gateway/assets/20288327/adc8bb58-0954-4cdd-b406-404ccf521102)

https://hub.docker.com/r/obsidiandynamics/kafdrop

I test your changes, for it to work the port must be the internal port of kafka as it communicates within the docker network in this case `9092`.

![imagen](https://github.com/adempiere/adempiere-ui-gateway/assets/20288327/87491ddd-b289-4a45-bca7-8360c6569de1)


The topic was created by exporting only the dictionary definition of the `SmartBrowse`.


A suggestion is not to use the latest version, but specify the version, because today your latest is the `sha256:e71b1cc1dd25` if tomorrow they publish another version, change the sha256 and on my machine or server may be another version different from yours, this way we ensure that it is always the same version that we all handle.

![imagen](https://github.com/adempiere/adempiere-ui-gateway/assets/20288327/956142f3-6b37-46f3-a38b-4357ea18e0e9)



```yml
  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    ports:
      - 19000:9000  # 9000 collides with s3.storage
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - adempiere_network
```
